services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
    networks:
      - cache-lab-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-changeme} --appendonly yes --maxmemory 1550kb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - cache-lab-network

networks:
  cache-lab-network:
    external: true